#' -----------------------------------------------------------------------------
#' Plot heatmap of enrichment/depletion in gene regulatory features (eFORGE)
#' 
#' @details This script reads in enrichment and depletion results generated by 
#' running the eforge.pl script, calculates p-values for one-tailed permutation test, 
#' and generates a heatmap showing log2 fold enrichment calculated by comparing 
#' sentinel CpG overlap to the mean overlap of the 1000 background sets 
#'
#' @author Konstanze Tan <konstanz001@e.ntu.edu.sg>. Adapted from: Dr Pritesh 
#' R. Jain.
#'
#' @date Thurs Mar 7 2024
#' -----------------------------------------------------------------------------

# Load required libraries 
library(ggplot2)
library(ggnewscale)

#' -----------------------------------------------------------------------------
# Format results for plotting (example: analysis of Roadmap chromatin states) 

# Read in enrichment results, calculate p-value
setwd("~/path/to/enrichment/results")
chromstates_enr_results <- read.table('erc2-chromatinstate.850k.erc2-chromatin15state-all.chart.tsv.gz', header = TRUE, sep='\t')
chromstates_enr_backg <- read.delim("background.tsv.gz", header=FALSE, sep="\t")
chromstates_enr_results$Pval_Enrichment <- 1/1001 * rowSums(chromstates_enr_backg[, 2:1001] > chromstates_enr_results$TestStat, na.rm=TRUE)

# Read in depletion results and background, calculate p-value
setwd("~/path/to/depletion/results")
chromstates_depl_results <- read.table('erc2-chromatinstate.depletion.850k.erc2-chromatin15state-all.chart.tsv.gz', header = TRUE, sep='\t')
chromstates_depl_backg <- read.delim("background.tsv.gz", header=FALSE, sep="\t")
chromstates_depl_results$Pval_Depletion <- 1/1001 * rowSums(chromstates_depl_backg[, 2:1001] < chromstates_depl_results$TestStat, na.rm=TRUE)

# Merge enrichment and depletion dataframes
chromstates_all_results <- cbind(chromstates_enr_results, chromstates_depl_results[, "Pval_Depletion"])
names(chromstates_all_results)[13] <- "Pval_Depletion"

# Calculate log2 fold enrichment (log2FE)
chromstates_all_results$Log2FE <- log2(chromstates_all_results$TestStat / (chromstates_all_results$Random.set.Overlap / 1000))

#' -----------------------------------------------------------------------------
# Prepare for plotting
All_results <- chromstates_all_results
All_results$Category <- "CHR" # indicate regulatory feature: CHR, histone or DHS

# Select tissue
All_results <- subset(All_results, Tissue == "Blood")

Cells <- unique(All_results$Cell)
All_results$Log2FE <- ifelse(All_results$Log2FE <= -2, -2, All_results$Log2FE)
All_results$Log2FE <- ifelse(All_results$Log2FE >= 2, 2, All_results$Log2FE)
All_results$Log2FE <- ifelse(is.na(All_results$Log2FE), 0, All_results$Log2FE)
All_results$Log2FE <- ifelse(All_results$TestStat == 0, NA, All_results$Log2FE)

Datatype_order <- c("TssA", "TssAFlnk", "TxFlnk", "Tx", "TxWk", "EnhG", "Enh", "ZNF-Rpts", "Het",
                    "TssBiv", "BivFlnk", "EnhBiv", "ReprPC", "ReprPCWk", "Quies")
All_results$Datatype <- factor(All_results$Datatype, levels = Datatype_order)

All_results$Signif <- ifelse(All_results$Pval_Enrichment <= 0.05 | All_results$Pval_Depletion <= 0.05, "p < 0.05", "non-sig")
All_results$Signif <- ifelse(All_results$Pval_Enrichment <= 0.001 | All_results$Pval_Depletion <= 0.001, "p < 0.001", All_results$Signif)
All_results$Signif <- ifelse(All_results$TestStat == 0, "non-sig", All_results$Signif)
All_results$Signif <- factor(All_results$Signif, levels = c("non-sig", "p < 0.001", "p < 0.05"))

# Generate the heatmap
png("Results-Enrichment.png", height = 10, width = 20, units = "cm", res = 480)
ggplot(All_results, aes(x = Datatype, y = Cell, fill = Log2FE)) +
  geom_tile() +
  scale_fill_gradient2(low = "skyblue3", high = "orangered3", mid = "white",
                       limit = c(-2, 2), breaks = c(-1.5, -0.75, 0, 0.75, 1.5),
                       labels = c("< -1.5", "-0.75", "0", "0.75", "> 1.5")) +
  labs(fill = "Log2(FC)") +
  new_scale("fill") +
  geom_point(aes(color = Signif, fill = Signif, shape = Signif), size = 0.6) +
  scale_shape_manual("Significance", values = c(NA, 21, 21)) +
  scale_color_manual("Significance", values = c(NA, "darkred", "darkred")) +
  scale_fill_manual("Significance", values = c(NA, "darkred", "white")) +
  scale_y_discrete(limits = rev(Cells)) +
  facet_grid(. ~ Category, scales = "free", space = "free") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 6),
    axis.text.y = element_text(size = 6),
    strip.text = element_text(size = 6, face = "bold"),
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    legend.key.size = unit(0.35, "cm"),
    legend.text = element_text(size = 6),
    legend.title = element_text(size = 6, face = "bold")
  )
dev.off()
